# Header
menu:
  Community: https://community.rockgolem.com
  Archives: /archives

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive
- links
thumbnail: true

# Contacts
contacts:
  github: http://github.com/rockgolem
  twitter: https://twitter.com/rockgolemgames
  facebook: https://www.facebook.com/rockgolemgames
  rss: /atom.xml

# Links
links:

# Feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: rockgolemgames
google_plus:
fb_admins:
fb_app_id:
